version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=mass_assignment
    volumes:
      - .:/var/www/html
    networks:
      - mass_assignment_network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mass_assignment
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql
    networks:
      - mass_assignment_network

networks:
  mass_assignment_network:
    driver: bridge

volumes:
  mysql_data:
